name: Ubuntu

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Install Build Dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libsdl2-dev
          sudo apt install gcc-10 g++-10

      - name: Create Build Environment
        shell: bash
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        env:
          CC: gcc-10
          CXX: g++-10
        run: cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build -D CMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        shell: bash
        env:
          CC: gcc-10
          CXX: g++-10
        run: cmake --build ${{runner.workspace}}/build --config $BUILD_TYPE
