name: Windows

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        shell: powershell
        run: cmake.exe -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: powershell
        run: cmake.exe -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -D CMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        shell: powershell
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE
